### PR TITLE
import macOS fixes from blaztinn/macos

### PR DESCRIPTION
**Pull request by illwieckz**
Import macos fixes from `blaztinn/macos`, see:

- https://github.com/Unity-Technologies/crunch/pull/15

The `crnlib` was already buildable on macOS when integrated in another software (like the Dæmon engine or the Netradiant editor), but not the `crunch` command line tool.

The branch also features some other minor fixes around that are probably not bad.

The macOS crunch tool builds and runs, tested on amd64 macOS Mojave.

---

_Part of original message:_

This PR still builds on Linux and Windows.

This PR doesn't build on macOS yet because cd8353d6e0fdfc5e2da0e6929b188334ed31e14a introduced this:

```
In file included from crunch/crnlib/crn_threading.h:7:
crunch/crnlib/crn_threading_pthreads.h:177:40: warning: defaulted function
      definitions are a C++11 extension [-Wc++11-extensions]
    virtual ~executable_task( void ) = default;
                                       ^
crunch/crnlib/crn_threading_pthreads.h:253:11: error: exception specification
      of overriding function is more lax than base version
  virtual ~object_task( void ) = default;
          ^
crunch/crnlib/crn_threading_pthreads.h:177:13: note: overridden virtual
      function is here
    virtual ~executable_task( void ) = default;
            ^
crunch/crnlib/crn_threading_pthreads.h:253:34: warning: defaulted function
      definitions are a C++11 extension [-Wc++11-extensions]
  virtual ~object_task( void ) = default;
                                 ^
make[2]: *** [crnlib/CMakeFiles/crn-obj.dir/crn_dds_comp.cpp.o] Error 1
make[2]: *** [crnlib/CMakeFiles/crn-obj.dir/crn_image_utils.cpp.o] Error 1
make[2]: *** [crnlib/CMakeFiles/crn-obj.dir/crn_dxt_image.cpp.o] Error 1
```

If I temporarily revert cd8353d6e0fdfc5e2da0e6929b188334ed31e14a the build continues but then the linkage fails:

```
[ 92%] Built target crn-obj
[ 94%] Linking CXX shared library libcrn.dylib
[ 94%] Linking CXX static library libcrn.a
duplicate symbol __ZN6crnlib5utils10write_le64EPvy in:
    CMakeFiles/crn-obj.dir/crn_arealist.cpp.o
    CMakeFiles/crn-obj.dir/crn_assert.cpp.o
[…]
ld: 994 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So,

1. We need to fix the `exception specification of overriding function is more lax than base version` error. @bmorel can you look at it? You're the one having introduced the commit triggering it so maybe you know what those errors are about… 🙂️

2. We need to fix the linkage error.

### CODE REVIEW

**Comment by illwieckz** [comment]
I also imported the fix by @blaztinn from:

- https://github.com/Unity-Technologies/crunch/pull/14

**Comment by illwieckz** [comment]
Maybe the bug about reading file on NFS on macOS is not a macOS specific bug but a generic crunch bug about the way it does file access and specificity of network file system, I would have to test NFS on other platforms to know more. I don't see that issue as a blocking issue for this merge, as the tool can actually be built and converts properly images to and from crn on macOS.

**Comment by illwieckz** [comment]
A test on apple M1 would also be nice.

**Comment by illwieckz** [comment]
As an alternative to the `extern CRNLIB_FORCE_INLINE` stuff, we may also be able to do this ([from this other branch implementing macOS support](https://github.com/xuewuli/crunch/blob/8cc3dd084f41b807a04c78db8f5700faa68380e4/crnlib/crn_core.h#L89-L93)):

```c++
#ifdef __APPLE__
#define CRNLIB_FORCE_INLINE inline __attribute__((__always_inline__))
#else
#define CRNLIB_FORCE_INLINE inline __attribute__((__always_inline__, __gnu_inline__))
#endif
```

**Review by DolceTriade — APPROVED** [review]
didn't test but seems ok

**Comment by illwieckz** [comment]
I noticed this implementation, like [this other one](https://github.com/DaemonEngine/crunch/commit/3a445a94cde7fb5cc26e677322785e7e85531a10) or [this other one](https://github.com/xuewuli/crunch/blob/8cc3dd084f41b807a04c78db8f5700faa68380e4/crnlib/crn_vector.cpp#L23-L24) is implementing the second fix discussed in https://github.com/DaemonEngine/crunch/issues/14 in addition to the first one we already do.

I guess it's harmless, and [this other macOS patch for macOS](https://github.com/xuewuli/crunch/blob/8cc3dd084f41b807a04c78db8f5700faa68380e4/crnlib/crn_vector.cpp#L23-L24) is know to already do both fixes.

**Pull request merged**
